test:
  adapter: mysql2
  host: localhost
  pool: 5
  username: root
  password: pa$$word
  encoding: utf8
  socket: /tmp/mysql.sock
  database: tradesanio_db_test

development:
  adapter: mysql2
  host: localhost
  pool: 5
  username: root
  password: pa$$word
  encoding: utf8
  socket: /tmp/mysql.sock
  database: tradesanio_db_dev


production:
  database: tradesanio_db_prod
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>